import Head from 'next/head'
import { useState } from 'react'
import { AiFillInstagram, AiFillFacebook, AiFillLinkedin } from 'react-icons/ai'
import { FaMapMarkerAlt } from 'react-icons/fa'
import { IoLogoWhatsapp } from 'react-icons/io'
import { MdEmail } from 'react-icons/md'

import * as S from '../components/Header/styles'
import { Card } from 'components/Card'
import { MyCarousel } from 'components/Carousel/indesx'
import { Header } from 'components/Header'

interface CardInfo {
  image: string
  title: string
  text: string
}

export default function Home() {
  const scrollToSection = () => {
    const bottomSection = document.getElementById('bottom')
    if (bottomSection) {
      bottomSection.scrollIntoView({ behavior: 'smooth' })
    }
  }

  const [listaCard] = useState<CardInfo[]>([
    {
      image: '/card6.png',
      title: 'ABRIR MEU MEI',
      text: 'Escolher corretametne  o CNAE do CNPJ é primordial, pois evitará problemas  na emissão das notas fiscais,  e  taxação de impostos.'
    },
    {
      image: '/card5.png',
      title: 'DECLARAÇÃO DASN MEI',
      text: 'Orientação no envio da Declaração de Faturamento Anual (DASN)'
    },
    {
      image: '/card4.png',
      title: 'ASSINAR CARTEIRA MEI',
      text: 'Orientação da folha de pagamento MEI'
    },
    {
      image: '/card2.png',
      title: 'EMISSÃO DE ALVARÁS',
      text: 'MEI também precisa de alvará de funcionamento e sanitário!'
    },
    {
      image: '/card7.png',
      title: 'CONSUTAR DEBITOS MEI',
      text: 'Regularização dos boletos DAS em atraso, e emissão das guias'
    },
    {
      image: '/card8.png',
      title: 'SAIR DO MEI PARA ME',
      text: 'Assessoria na alteração dos dados para uma transição de CNPJ MEI para ME, ou retornar para MEI de forma segura '
    },
    {
      image: '/card1.png',
      title: 'CANCELAR MEI',
      text: 'Auxilio no cancelamento do MEI, sem correr riscos de ficar com débitos.'
    },
    {
      image: '/card3.png',
      title: 'EMISSÃO DAS NOTAS FISCAIS',
      text: 'Orientação da emissão das Notas Fiscais e cálculos tributários.'
    }
  ])

  return (
    <>
      <Head>
        <title>Contabiliza meu MEI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon.icon" type="image/x-icon" />
      </Head>
      <main>
        <Header />
        <S.Content>
          <S.Title>
            <p>
              ASSESSORIA para ter seu <br /> CNPJ MEI <br /> sem complicação!
            </p>
          </S.Title>

          <S.More onClick={scrollToSection}>Veja todas as vantagens</S.More>
        </S.Content>

        <S.Information>
          <p>Tenha assessoria contábil a partir de R$25,00 mensais!!!</p>
        </S.Information>
        <S.BgContainer id="bottom" className="Container">
          <S.ColumnsContainer>
            <S.Column>
              {listaCard
                .slice(0, Math.ceil(listaCard.length / 2))
                .map((card, index) => (
                  <Card
                    key={index}
                    image={card.image}
                    title={card.title}
                    text={card.text}
                  />
                ))}
            </S.Column>
            <S.Column>
              {listaCard
                .slice(Math.ceil(listaCard.length / 2))
                .map((card, index) => (
                  <Card
                    key={index}
                    image={card.image}
                    title={card.title}
                    text={card.text}
                  />
                ))}
            </S.Column>
            <div className="d-md-none">
              <MyCarousel />
            </div>
          </S.ColumnsContainer>
          <S.Frase_e_Icon>
            <div>
              <S.Read>
                Tudo isso por apenas <br />
                R$25,00 mensais!!
              </S.Read>
            </div>
            <S.Icons>
              <a href="https://w.app/2wVKCy" target="_blank" rel="noreferrer">
                <IoLogoWhatsapp size={96} color="#DAA521" />
              </a>
            </S.Icons>
          </S.Frase_e_Icon>
        </S.BgContainer>
        <S.BgContainer2>
          <S.Footer>
            <div>
              <h4>CONTATE - NOS</h4>
            </div>
            <div>
              <S.Others>Outros Serviços</S.Others>
            </div>
            <div>
              <S.Others2>Trabalhe Conosco</S.Others2>
            </div>
          </S.Footer>
          <S.ContentFooter>
            <S.IconsFooter>
              <S.AllIcon>
                <AiFillFacebook size={20} color="#0000FF" />
                <a
                  href="https://instagram.com/contacleo?igshid=MzRlODBiNWFlZA=="
                  target="_blank"
                  rel="noreferrer"
                >
                  <AiFillInstagram size={20} color="#0000FF" />
                </a>
                <AiFillLinkedin size={20} color="#0000FF" />
                <IoLogoWhatsapp size={20} color="#0000FF" />
                <MdEmail size={20} color="#0000FF" />
              </S.AllIcon>
              <S.Adress>
                <FaMapMarkerAlt size={40} color="#0000FF" />
                <p>
                  Rua 36,n° 26,quadra B4 setor B. <br /> Santa Terezinha II,
                  Cuiabá - MT
                </p>
              </S.Adress>
            </S.IconsFooter>
            <S.Services>
              <S.ColumnsServices>
                <p>Declaração de Imposto de renda (física)</p>
                <p>Acompanhamento do Inss</p>
              </S.ColumnsServices>
              <S.ColumnsServices>
                <p>Pensão por morte</p>
                <p>Auxílio doença</p>
              </S.ColumnsServices>
              <S.ColumnsServices>
                <p>INSS pelo gov.</p>
                <p>LCTCD</p>
              </S.ColumnsServices>
            </S.Services>
            <S.Invite>
              <p>É contador ! Trabalhe conosco!!</p>
            </S.Invite>
          </S.ContentFooter>
        </S.BgContainer2>
      </main>
    </>
  )
}
